# Generated by Django 6.0.4 on 2026-09-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_unique_default_address_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Added to Wallet)'), ('DEBIT', 'Debit (Deducted from Wallet)')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('order_id', models.CharField(blank=True, help_text='Associated Order ID if applicable', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date and time when this credit expires. None means never.', null=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining unused amount of this credit transaction.', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_walle_user_id_1926ef_idx'), models.Index(fields=['user', 'transaction_type'], name='users_walle_user_id_b956c8_idx')],
            },
        ),
    ]
