# Generated by Django 6.0.4 on 2026-09-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='remaining_amount',
        ),
    ]
