# Generated by Django 6.0.4 on 2026-09-04 15:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_wallettransaction_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this credit expires. None means perpetual (never expires).', null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining unused balance of this credit grant.', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', 'transaction_type', 'remaining_amount', 'expires_at'], name='idx_wallet_txn_fifo'),
        ),
    ]
