# Generated by Django 6.0.4 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_wallettransaction_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='idx_wallet_txn_user_fifo',
            old_name='idx_wallet_txn_fifo',
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'expires_at', 'remaining_amount'], name='idx_wallet_txn_global_exp'),
        ),
    ]
