# Generated by Django 6.0.4 on 2026-09-19 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive zone label (e.g. 'West Zone (Tier 1)', 'North East & Special States')", max_length=100, unique=True)),
                ('states', models.TextField(help_text="Comma-separated list of state names or codes (e.g. 'Maharashtra, Gujarat, Goa')")),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Standard delivery fee for this geographic zone', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Zone override for free shipping threshold. Leave blank to inherit site settings default.', max_digits=10, null=True)),
                ('cod_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Zone override for COD fee. Leave blank to inherit site settings default.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active zones are evaluated during rate resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Modern Storefront', help_text='Public brand name displayed across the storefront', max_length=150)),
                ('contact_email', models.EmailField(blank=True, help_text='Customer support email address', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Customer support contact phone number', max_length=30, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical headquarters or registered business address', null=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, non-admin checkout and order placement are disabled')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required to proceed to checkout', max_digits=10)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Default flat shipping fee applied if zone shipping is disabled or unlisted', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('999.00'), help_text='Cart subtotal threshold at or above which shipping is free', max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Flat handling surcharge applied to Cash On Delivery (COD) orders', max_digits=10)),
                ('is_zone_shipping_enabled', models.BooleanField(default=False, help_text='When enabled, dynamic geographic zones override global shipping rates')),
                ('partial_cod_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of order total required as advance deposit for COD orders (0 to 100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
