# Generated by Django 6.0.4 on 2026-09-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Human-readable category name.', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly unique identifier.', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Category banner or card thumbnail.', null=True, upload_to='categories/')),
                ('show_in_header', models.BooleanField(db_index=True, default=False, help_text='Display in top navigation bar dropdown menus.', verbose_name='Show in Header Menu')),
                ('show_on_homepage', models.BooleanField(db_index=True, default=True, help_text='Display in storefront landing page category grid.', verbose_name='Show on Homepage')),
                ('header_order', models.PositiveIntegerField(default=0, help_text='Ascending sort order for header navigation menu.', verbose_name='Header Sort Order')),
                ('homepage_order', models.PositiveIntegerField(default=0, help_text='Ascending sort order for homepage category grid.', verbose_name='Homepage Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category. If null, this is a top-level root department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['header_order', 'name'],
                'indexes': [models.Index(fields=['parent', 'header_order'], name='idx_category_parent_order'), models.Index(fields=['show_in_header', 'header_order'], name='idx_category_header_menu'), models.Index(fields=['show_on_homepage', 'homepage_order'], name='idx_category_homepage')],
            },
        ),
    ]
