# Generated by Django 6.0.4 on 2026-09-09 08:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product title displayed across catalog and product pages.', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly unique product slug.', max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base catalog selling price or starting variant price.', max_digits=10, verbose_name='Base Price (₹)')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original strike-through Maximum Retail Price (MRP) for discount calculation.', max_digits=10, null=True, verbose_name='Compare-at / MRP (₹)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Procurement or manufacturing unit cost for gross profit margin analysis.', max_digits=10, verbose_name='Cost Price (₹)')),
                ('short_description', models.CharField(blank=True, help_text='Concise summary snippet for catalog cards and search previews.', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed HTML or Markdown product description.', verbose_name='Long Description')),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='Summed available stock across all child variants or standalone inventory.', verbose_name='Total Aggregated Stock')),
                ('in_stock', models.BooleanField(db_index=True, default=True, help_text='Instant boolean availability flag.', verbose_name='In Stock')),
                ('is_live', models.BooleanField(db_index=True, default=True, help_text='Master visibility toggle for storefront catalog listing.', verbose_name='Is Live on Storefront')),
                ('is_hero', models.BooleanField(db_index=True, default=False, help_text='Spotlight featured banner product on the storefront homepage.', verbose_name='Hero Product')),
                ('is_popular', models.BooleanField(db_index=True, default=False, help_text='Highlight in recommendation carousels and slide-out cart drawers.', verbose_name='Popular Right Now')),
                ('is_combo', models.BooleanField(db_index=True, default=False, help_text='Designates a multi-item combo or bundled gift set.', verbose_name='Combo Deal / Bundle')),
                ('variant_name', models.CharField(blank=True, help_text="Label for primary variant dimension (e.g., 'Size', 'Color', 'Bundle Pack').", max_length=50, null=True, verbose_name='Variant Dimension Label')),
                ('variants', models.JSONField(blank=True, default=list, help_text="JSON list of variant attribute options (e.g., [{'name': 'Size', 'options': ['S', 'M', 'L']}]).", verbose_name='Variant Attribute Schema')),
                ('metafields', models.JSONField(blank=True, default=dict, help_text='Flexible key-value pairs for specifications (fabric, care, origin, warranty).', verbose_name='Custom Metafields')),
                ('gst_rate', models.DecimalField(choices=[(Decimal('3.00'), '3% (Gold & Precious Metals)'), (Decimal('5.00'), '5% (Apparel under ₹1,000 & Essentials)'), (Decimal('12.00'), '12% (Standard Apparel & Accessories)'), (Decimal('18.00'), '18% (Consumer Goods & Electronics)'), (Decimal('28.00'), '28% (Luxury & Premium Items)')], decimal_places=2, default=Decimal('12.00'), help_text='Applicable Goods and Services Tax (GST) bracket.', max_digits=5, verbose_name='GST Slab Rate (%)')),
                ('hsn_code', models.CharField(blank=True, help_text='Harmonized System of Nomenclature code for statutory invoice compliance.', max_length=20, null=True, verbose_name='HSN / SAC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary category taxonomy node. Protected against accidental deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant label (e.g., 'Red / XL', '128GB / Midnight Black', 'Pack of 3').", max_length=255, verbose_name='Variant Name')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional variant-specific selling price. If omitted, inherits parent price.', max_digits=10, null=True, verbose_name='Price Override (₹)')),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='Current available inventory for this discrete SKU.', verbose_name='SKU Stock Count')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Unique inventory tracking code across the entire warehouse.', max_length=100, null=True, unique=True, verbose_name='Stock Keeping Unit (SKU)')),
                ('image', models.ImageField(blank=True, help_text='Optional variant-specific product photo.', null=True, upload_to='variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Parent product owning this variant.', on_delete=django.db.models.deletion.CASCADE, related_name='variants_list', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_live', 'category'], name='idx_product_live_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_live', 'is_popular'], name='idx_product_live_popular'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_live', 'is_hero'], name='idx_product_live_hero'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_live', 'price'], name='idx_product_live_price'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'stock_count'], name='idx_variant_prod_stock'),
        ),
    ]
