# Generated by Django 6.0.4 on 2026-09-09 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0% (Exempt Essentials & Unprocessed Goods)'), (Decimal('3.00'), '3% (Gold, Silver & Precious Jewelry)'), (Decimal('5.00'), '5% (Apparel, Footwear & Everyday Essentials)'), (Decimal('18.00'), '18% (Standard Consumer Goods, Electronics & Services)'), (Decimal('40.00'), '40% (Luxury, Premium Demerit & Sin Goods)')], decimal_places=2, default=Decimal('5.00'), help_text='Applicable statutory Goods and Services Tax (GST) bracket.', max_digits=5, verbose_name='GST Slab Rate (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text="Harmonized System of Nomenclature code (e.g., '62052000' for men's cotton shirts) for statutory invoice compliance.", max_length=20, null=True, verbose_name='HSN / SAC Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, help_text='Available inventory units (managed directly or synchronized with child variants in Chapter 13).', verbose_name='Stock Count'),
        ),
    ]
