# Generated by Django 6.0.4 on 2026-09-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_gst_rate_alter_product_hsn_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product photograph (automatically compressed to WebP).', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive image caption for SEO and screen readers.', max_length=255, verbose_name='Alt Text / Accessibility Label')),
                ('is_thumbnail', models.BooleanField(db_index=True, default=False, help_text='Designates this image as the primary catalog card thumbnail.', verbose_name='Is Primary Thumbnail')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ascending sequence for storefront carousel and gallery view.', verbose_name='Display Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Parent product owning this gallery image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional variant mapping (e.g., specific colorway photo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['product', 'order'], name='idx_prod_img_order'), models.Index(fields=['product', 'is_thumbnail'], name='idx_prod_img_thumb')],
            },
        ),
    ]
