# Generated by Django 6.0.4 on 2026-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_thumbnail', True)), fields=('product',), name='unique_primary_thumbnail_per_product'),
        ),
    ]
