# Generated by Django 6.0.4 on 2026-09-16 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage_unique_primary_thumbnail_per_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Anonymous session identifier or user token.', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address for telemetry and geolocation.', null=True)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('region', models.CharField(default='Unknown', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.FloatField(default=20.5937)),
                ('longitude', models.FloatField(default=78.9629)),
                ('current_page', models.CharField(default='Shop', max_length=255)),
                ('action', models.CharField(default='viewing', help_text='Current shopper intent action: viewing, cart, checkout, purchased.', max_length=50)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Active Visitor',
                'verbose_name_plural': 'Active Visitors',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Customer satisfaction rating from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating')),
                ('comment', models.TextField(blank=True, default='', help_text='Detailed customer feedback and experience description.', verbose_name='Review Comment')),
                ('verified_purchase', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the author had a verified, delivered order for this product.', verbose_name='Verified Purchase')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Moderation flag controlling public storefront visibility.', verbose_name='Approved for Display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(help_text='User who authored the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Customer photo attachment (automatically optimized to WebP).', upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(help_text='Parent review owning this image attachment.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Saved catalog products.', related_name='wishlisted_by', to='catalog.product')),
                ('user', models.OneToOneField(help_text='User owning this saved wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='idx_rev_prod_app_date'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='idx_rev_user_date'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_user_product_review'),
        ),
    ]
