# Generated by Django 6.0.4 on 2026-09-17 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_review_rating_between_1_and_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier for unauthenticated guest visitors.', max_length=255, null=True)),
                ('abandoned_email_sent', models.BooleanField(default=False, help_text='Indicates whether an abandoned cart recovery notification has been dispatched.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Authenticated customer owning this cart. Null for guest sessions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units added to cart (must be >= 1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Parent cart container.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(help_text='Referenced catalog product.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Specific child SKU variant selection, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='idx_cart_session_key'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', '-updated_at'], name='idx_cart_user_updated'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key',), name='unique_session_cart'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='cart_has_user_or_session'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='idx_cartitem_cart_prod'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'product', 'variant'), name='unique_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_no_variant'),
        ),
    ]
